 #Python CircleCI 2.0 configuration file
#
# Inspired by: https://github.com/spatialaudio/nbsphinx/blob/master/.circleci/config.yml
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build_docs:
    docker:
      # https://github.com/dante-ev/docker-texlive
      - image: danteev/texlive

    working_directory: ~/checkout

    environment:
      PIP_INSTALL: python3 -m pip install --user --progress-bar off --upgrade

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "requirements.txt" }}
            # fallbacks
            - v1-deps-{{ .Branch }}-
            - v1-deps-

      - run:
          name: Installing nbsphinx
          command: |
            $PIP_INSTALL .
      - run:
          name: Installing doc Dependencies
          command: |
            $PIP_INSTALL -r requirements.txt
      - save_cache:
          paths:
            - ~/.cache/pip
          key: v1-deps-{{ .Branch }}-{{ checksum "requirements.txt" }}

      - run:
          name: Installing apt Packages
          command: |
            apt-get update
            apt-get install -y librsvg2-bin
      - run:
          name: Building HTML - there is no cache atm?
          command: |
            python3 -m sphinx . build
      - run:
          name: Pushing to gh-pages
          command: |
            ghp-import -p -n -f -r https://${GITHUB_PERSONAL_TOKEN}@github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}.git build
workflows:
  version: 2
  build-me-my-docs:
    jobs:
      - build_docs